[params]
  languageIcon  = ":uk:"
  [params.events]
      datefmt   = "Mon Jan 2. 15:04"#":date_short"
      title     = "Upcoming events"
      subtitle  = "Crafting experiences and character."

  # Banner Section
  [params.banner]
      logo                  = "images/logo.svg"
      down_arrow            = "images/arrow-down.svg"
  [params.banner_txt]
    primary_button        = "Become a member"
    primary_button_url    = "/#memberships"
  [params.call_to_action]
    primary_button      = "Become a member"
    primary_button_url  = "memberships"
  [params.gallery]
    title = "WHAT WE DO HERE"
    path_match = "images/gallery/*"