[privacy]
# Disable trackers for embedded content using these shortcodes.
# Does not affect content delivery afaik.
[privacy.disqus]
    disable = true
[privacy.googleAnalytics]
    disable = false
    anonymizeIP = true           # optional but recommended
    respectDoNotTrack = true     # optional
    useSessionStorage = false    # optional, default is fine[privacy.instagram]
[privacy.twitter]
    disable = true
[privacy.vimeo]
    disable = true
[privacy.youtube]
    disable = true